// theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;

export const USER_LOGIN = 'USER_LOGIN';
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN';
export const ERROR_USER_LOGIN = 'ERROR_USER_LOGIN';

export const USER_DETAILS = 'USER_DETAILS';
export const SUCCESS_USER_DETAILS = 'SUCCESS_USER_DETAILS';
export const ERROR_USER_DETAILS = 'ERROR_USER_DETAILS';

export const GET_CANDIDATES = 'GET_CANDIDATES';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_ERROR = 'GET_CANDIDATES_ERROR';

export const GET_CANDIDATES_BY_ID = 'GET_CANDIDATES_BY_ID';
export const GET_CANDIDATES_BY_ID_SUCCESS = 'GET_CANDIDATES_BY_ID_SUCCESS';
export const GET_CANDIDATES_BY_ID_ERROR = 'GET_CANDIDATES_BY_ID_ERROR';
